language: cpp
os: linux
dist: trusty
sudo: required
cache: 
  directories:
    - $HOME/deps/abc
    - $HOME/.ccache

env:
  global:
    - COMPILER=g++-8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - libboost-program-options1.55.0
      - libboost-program-options1.55-dev
      - lcov
      - gcovr
      - python-numpy
      - python-matplotlib

before_install:
#removes speed limit on downloads
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
install:
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.0-rc3-Linux-x86_64.tar.gz"
  - mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - ./deps_install.sh

script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
  - make
  - cd ..
  - python basic_tests.py --travis

notifications:
  slack:
    secure: GdtRuYo8zwdwUGJR9wan4gXAF58E0mrxofS6vByLFtXiN2RCEdE8kajyv6pbxJQT2+lV0jfWTHcq5ZscW2gJFAcw/ND7CJTzsz8C0TrLW622WJTDAyhyXxJNZKmW8qTi2nbW8xG9X0xPwKKhhJK0eb99A+4klYXG55ctEXyFRPCxRxM1M3q1ekJP6H/WBkje/H0118DQH92lFhSRjUxAAWxeGUu8NRqYC3bN4zdS6mmuU9e5JqOAaaDuo386Om8yEbXQf7oi6IantmkA8oXeuZK6gdMBUZUl6a18xtRq3p1292mRYlwjWsuTSHIsl52bqp0sTjgfAVe4pmpvpuKRE5BYd3QeyWnSu0KQaK3PcRapde6KSd8cqskwbIXFQbV1/SYH1ZrGAPxe0J93lllKYIiMim1zWTegWXsER5iFXGId4euDWboDx3ZiVBtmpP34vA8U+bFP147rO7aSr+YLTAPSEqX98ugNm8wd3bjCZWZ/HRuowQr64mDtes5XNdI8iWKIAIoKKbEfAO+Y2FRgUtkOiuk37VsN1vamM97qd7ex0mfxq6jOivwNkv8pxcqAmr0EKGFyhPEKYlx0n4jClcATiA/NOQshUkkpvh1CoVX6OwX+WwxvKSpBLKkhG43rLOwztz1LH/C68Cn6eVSseAUQIug5G79q8/Cqnc//RNo=
